server:
  port: 8080

spring:
  application:
    name: water-article

eureka:
  client:
    serviceUrl:
      defaultZone: http://machinedog.yipzale.me:1111/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

mybatis:
  type-aliases-package: me.yipzale.water.article.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#logging:
#  level:
#    me.yipzale.water.article.mapper: DEBUG

datasource:
  master:
    url: jdbc:mysql://mysql:3306/water?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: leaf
    password: leaf
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true
  slave:
    - url: jdbc:mysql://mysql-slave:3306/water?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: leaf
      password: leaf
      initial-size: 5
      min-idle: 1
      max-active: 100
      test-on-borrow: true