server:
  port: 8080

spring:
  application:
    name: water-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://machinedog.yipzale.me:1111/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

mybatis:
  type-aliases-package: me.yipzale.water.article.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

