package me.yipzale.water.article.entity;

public class ArticleContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_contents.id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_contents.article_id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_contents.content
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_contents.id
     *
     * @return the value of article_contents.id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_contents.id
     *
     * @param id the value for article_contents.id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_contents.article_id
     *
     * @return the value of article_contents.article_id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_contents.article_id
     *
     * @param articleId the value for article_contents.article_id
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_contents.content
     *
     * @return the value of article_contents.content
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_contents.content
     *
     * @param content the value for article_contents.content
     *
     * @mbg.generated Sat Jul 21 17:07:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}